### ISSUE TITLE
Getting TypeError: object of type 'Response' has no len()

### ISSUE THREAD

**Issue by Surbhi-sy** [zscaler/ziacloud-ansible#45]
Hello,
I am trying to fetch the locations management info from zscaler_ziacloud module in ansible. 
But getting the below error while executing the playbook:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_zscaler.ziacloud.zia_location_management_info_payload_zlfipp5r/ansible_zscaler.ziacloud.zia_location_management_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_location_management_info.py", line 280, in main
  File "/tmp/ansible_zscaler.ziacloud.zia_location_management_info_payload_zlfipp5r/ansible_zscaler.ziacloud.zia_location_management_info_payload.zip/ansible_collections/zscaler/ziacloud/plugins/modules/zia_location_management_info.py", line 268, in core
  File "/usr/local/lib/python3.9/site-packages/zscaler/zia/locations.py", line 69, in list_locations
    return BoxList(Iterator(self.rest, "locations", **kwargs))
  File "box/box_list.py", line 51, in box.box_list.BoxList.__init__
  File "/usr/local/lib/python3.9/site-packages/restfly/iterator.py", line 114, in __next__
    return self.next()  # noqa: PLE1102
  File "/usr/local/lib/python3.9/site-packages/restfly/iterator.py", line 146, in next
    if len(self.page) == 0:
TypeError: object of type 'Response' has no len()

"msg": "object of type 'Response' has no len()"

**Comment by sandeepmuttineni222** [comment]
Me too getting the same error.... Please help regarding this error

**Comment by willguibr** [comment]
@Surbhi-sy @sandeepmuttineni222 
Can you provide the playbook example you're executing?
Also, can you indicate how many locations are currently present in your respective tenants?

Zscaler DevRel

**Comment by Surbhi-sy** [comment]
this is the playbook that I am using.
![image](https://github.com/user-attachments/assets/5e67a5f0-a990-45f4-8b66-0ef7d765fe1f)

There are around 30 locations available.

**Comment by willguibr** [comment]
@sandeepmuttineni222 and @Surbhi-sy 
We have been unable to reproduce the problem you're reporting.
Pease raise a case with the Zscaler support team, so that they can coordinate a call with our team for further investigation.
Thank you
Zscaler DevRel

**Comment by Surbhi-sy** [comment]
@willguibr, could you please provide me with the list of python packages and their version that are installed in your environment. so that i can match the same in my environment and analyze if there are any gaps.
Doing so might help us resolve the issue, if it is caused by different version of the python packages.

**Comment by Surbhi-sy** [comment]
> @sandeepmuttineni222 and @Surbhi-sy We have been unable to reproduce the problem you're reporting. Pease raise a case with the Zscaler support team, so that they can coordinate a call with our team for further investigation. Thank you Zscaler DevRel

hi, i have opened up a case with Zscaler support team regarding this issue and would like to have a connect with you and zscaler support team. Please let me know, how that can be arranged, will request zscaler support team to arrange the same.

**Comment by Surbhi-sy** [comment]
> > @sandeepmuttineni222 and @Surbhi-sy We have been unable to reproduce the problem you're reporting. Pease raise a case with the Zscaler support team, so that they can coordinate a call with our team for further investigation. Thank you Zscaler DevRel
> 
> hi, i have opened up a case with Zscaler support team regarding this issue and would like to have a connect with you and zscaler support team. Please let me know, how that can be arranged, will request zscaler support team to arrange the same.

@willguibr, please suggest a way so that I can schedule a call with with you zscaler support team.

**Comment by willguibr** [comment]
@sandeepmuttineni222 Please upgrade the collection to the latest version v2.0.0.
Prior to attempting to use please refer to the documentation for authentication details.

Zscaler DevRel
